# This file contains values from Cookiecutter

default_context:
  project_name: "humblepy"
  project_description: "Tasty recipes for analytics engineering."
  organization: "OKTIV Analytics"
  license: "Apache Software License 2.0"
  minimal_python_version: 3.9
  github_name: "OKTIVAnalytics"
  email: "humblepy@oktivanalytics.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
