name: main

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install "mkdocstrings[python]"
      - name: Deploy MkDocs
        run: mkdocs gh-deploy --force --clean --verbose
